language: node_js
node_js:
 - "node"

jobs:
  include:
    - stage: npm release
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true